spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/unit-testing?createDatabaseIfNotExist=true&&serverTimezone=UTC}
    username: root
    password:
  jpa:
    show-sql: true
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update